STUDY_ID = "studyId"
TASK_ID = "taskId"
DICOM = "dicom"
OUTPUT_PATH_PREFIX = "output_path_prefix"
INPUT = "input"
SERIES_EXTRACTION_QC = "series_extraction_qc"
ID = "id"
OUTPUT = "output"
SUBTASK_NAME = "moz-series-extraction"

SERIES_DESCRIPTION = "SeriesDescription"
SERIES_NUMBER = "SeriesNumber"
GRID_PERIOD = "GridPeriod"
PIXEL_SPACING = "PixelSpacing"
SLICE_THICKNESS = "SliceThickness"
MODALITY = "Modality"
CT = "CT"
INSTANCE_NUMBER = "InstanceNumber"
